SuperSite/SuperSite/Controllers/PayPalController.cs
using SuperSite.Context;
using SuperSite.Models;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace SuperSite.Controllers
{
    public class PayPalController : Controller
    {
        TransactionContext db = new TransactionContext();
        PayPalContext pp = new PayPalContext();
        
        public ActionResult Index()
        {

            return View(db.Stocks.ToList());
        }

        public ActionResult Success() {
            return View();
        }
        public ActionResult Details(int? id)
        {
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                PayPalCheckoutInfo payPalCheckoutInfo = pp.PayPalCheckoutInfoes.Find(id);
                if (payPalCheckoutInfo == null)
                {
                    return HttpNotFound();
                }
                return View(payPalCheckoutInfo);
            }
        }

        [AllowAnonymous]
        public EmptyResult PayPalPaymentNotification(PayPalCheckoutInfo payPalCheckoutInfo)
        {
            try
            {
               
                if (ModelState.IsValid)
                {
                    Response.AppendToLog("Final");
                    PayPalListenerModel model = new PayPalListenerModel();
                    model._PayPalCheckoutInfo = payPalCheckoutInfo;
                    byte[] parameters = Request.BinaryRead(Request.ContentLength);

                    if (parameters != null)
                    {
                        model.GetStatus(parameters);
                    }
                    pp.PayPalCheckoutInfoes.Add(payPalCheckoutInfo);
                    pp.SaveChanges();

                    Transaction Transaction = new Transaction(payPalCheckoutInfo); 
                    db.Transactions.Add(Transaction);
                    db.SaveChanges();                   
                }               
            }
            catch(Exception ex)
            {
                Response.AppendToLog("Invalid IPN model recieved");
                Response.AppendToLog(ex.ToString());
            }
             
            
            return new EmptyResult();
        }
    }
}

SuperSite/SuperSite/Controllers/StockController.cs
using SuperSite.Context;
using SuperSite.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SuperSite.Controllers
{
    [Authorize]
    public class StockController : Controller
    {
        public Site activeTheme { get; set; }
        ThemeContext themeDb = new ThemeContext();
        StockContext db = new StockContext();

        public void GetThemeAndSet()
        {
            SiteContext Sitedb = new SiteContext();
            activeTheme = Sitedb.Sites
                   .Where(b => b.isActive == 1)
                   .FirstOrDefault();
            if (activeTheme == null)
            {
                activeTheme = new Site();
                activeTheme.Theme = new Theme();
                activeTheme.Theme.CSSFileName = "css/style-blue.css";
            }
        }
              
        // GET: Stock
        public ActionResult Index()
        {                          
                return View(db.Stocks.ToList());    
        }
        public ActionResult CustomerIndex() {        
            return View("ShopFront", db.Stocks.ToList());
        }

        // GET: Stock/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
                Stock stock = db.Stocks.Find(id);
                if (stock == null)
                {
                    return HttpNotFound();
                }
                return View(stock);       
        }

        // GET: Stock/Create
        public ActionResult Create()
        {
            ViewData["Suppliers"] = db.Suppliers.ToList();
            return View();
        }

        // POST: Stock/Create
        [HttpPost]
        public ActionResult Create(Stock stock)
        {
            try
            {
                stock.PaypalButtonId = "N/A";
                if (ModelState.IsValid)
                {
                    var fileName = "";
                    var path = "";

                    var file1 = Request.Files[0];
                    if (file1 != null && file1.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file1.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file1.SaveAs(path);
                        stock.Filename1 = fileName;
                    }

                    var file2 = Request.Files[1];
                    if (file2 != null && file2.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file2.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file2.SaveAs(path);
                        stock.Filename2 = fileName;
                    }
                    var file3 = Request.Files[2];
                    if (file3 != null && file3.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file3.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file3.SaveAs(path);
                        stock.Filename3 = fileName;
                    }
                    var file4 = Request.Files[3];
                    if (file4 != null && file4.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file4.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file4.SaveAs(path);
                        stock.Filename4 = fileName;
                    }
                    var file5 = Request.Files[4];
                    if (file5 != null && file5.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file5.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file5.SaveAs(path);
                        stock.Filename5 = fileName;
                    }
                    var file6 = Request.Files[5];
                    if (file6 != null && file6.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file6.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file6.SaveAs(path);
                        stock.Filename6 = fileName;
                    }
                    var file7 = Request.Files[6];
                    if (file7 != null && file7.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file7.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file7.SaveAs(path);
                        stock.Filename7 = fileName;
                    }
                    var file8 = Request.Files[7];
                    if (file8 != null && file8.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file8.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file8.SaveAs(path);
                        stock.Filename8 = fileName;
                    }
                    var file9 = Request.Files[8];
                    if (file9 != null && file9.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file9.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file9.SaveAs(path);
                        stock.Filename9 = fileName;
                    }
                    var file10 = Request.Files[9];
                    if (file10 != null && file10.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file10.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file10.SaveAs(path);
                        stock.Filename10 = fileName;
                    }                
                    db.Stocks.Add(stock);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(stock);
            }
            catch
            {
                return View();
            }
        }

        // GET: Stock/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewData["Suppliers"] = db.Suppliers.ToList();
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Stock stock = db.Stocks.Find(id);
            if (stock == null)
            {
                return HttpNotFound();
            }
            return View(stock);
        }

        // POST: Stock/Edit/5
        [HttpPost]
        public ActionResult Edit(Stock stock)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    db.Entry(stock).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(stock);
            }
            catch
            {
                return View();
            }
        }

        // GET: Stock/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Stock stock = db.Stocks.Find(id);
            if (stock == null)
            {
                return HttpNotFound();
            }
            return View(stock);
        }

        // POST: Stock/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id, Stock stockk)
        {
            try
            {
                Stock stock = new Stock();
                if (ModelState.IsValid)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    stock = db.Stocks.Find(id);
                    if (stock == null)
                    {
                        return HttpNotFound();
                    }
                    db.Stocks.Remove(stock);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(stock);
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperSite/SuperSite/Controllers/TransactionController.cs
using SuperSite.Context;
using SuperSite.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SuperSite.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
     
        public Site activeTheme { get; set; }

        ThemeContext themeDb = new ThemeContext();
        TransactionContext db = new TransactionContext();
       


        // GET: Transaction
        public ActionResult Index()
        {
           
            return View(db.Transactions.ToList());
        }



        // GET: Transaction/Details/5
        public ActionResult Details(int? id)
        {
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                Transaction transaction = db.Transactions.Find(id);
                if (transaction == null)
                {
                    return HttpNotFound();
                }
                return View(transaction);
            }
        }

        // GET: Transaction/Create
        public ActionResult Create()
        {
            ViewData["Stocks"] = db.Stocks.ToList();
            return View();
        }
 

        // POST: Transaction/Create
        [HttpPost]
        public ActionResult Create(Transaction transaction)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Transactions.Add(transaction);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(transaction);
            }
            catch
            {
                return View();
            }
        }

        // GET: Transaction/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewData["Stocks"] = db.Stocks.ToList();
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: Transaction/Edit/5
        [HttpPost]
        public ActionResult Edit(Transaction transaction)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(transaction).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(transaction);
            }
            catch
            {
                return View();
            }
        }

        // GET: Transaction/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: Transaction/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id, Transaction transactionn)
        {
            try
            {
                Transaction transaction = new Transaction();
                if (ModelState.IsValid)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    transaction = db.Transactions.Find(id);
                    if (transaction == null)
                    {
                        return HttpNotFound();
                    }
                    db.Transactions.Remove(transaction);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(transaction);
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperSite/SuperSite/Views/Transaction/Create.cshtml
@model SuperSite.Models.Transaction

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.StockId, "Purchase item", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StockId", new SelectList((System.Collections.IEnumerable)ViewData["Stocks"], "StockId", "Name"))
                @Html.ValidationMessageFor(model => model.StockId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.quantity, "Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reference, "Additional information", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reference, "", new { @class = "text-danger" })
            </div>
        </div>*@
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SuperSite/SuperSite/Views/Transaction/Delete.cshtml
@model SuperSite.Models.Transaction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.stock.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stock.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SuperSite/SuperSite/Views/Transaction/Details.cshtml
@model SuperSite.Models.Transaction

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt style="padding:5px;">
            @Html.DisplayNameFor(model => model.PayPalCheckoutInfo.TransactionId)
        </dt>
        <dd style="padding:5px;">
            @Html.ActionLink(Model.PayPalCheckoutInfo.txn_id, "Details", "PayPal", new { @id = Model.PayPalCheckoutInfo.TransactionId }, new { @class = "ButtonLink" })           
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayPalCheckoutInfo.payer_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayPalCheckoutInfo.payer_id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PayPalCheckoutInfo.payer_status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayPalCheckoutInfo.payer_status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PayPalCheckoutInfo.payment_status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayPalCheckoutInfo.payment_status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Stock.Name)
        </dt>
        <dd>
            @Html.ActionLink(Model.Stock.Name, "Details", "Stock", new { @id = Model.StockId }, null)  
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IPNDateRecieved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IPNDateRecieved)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TransactionId }) |
    @Html.ActionLink("Home", "Index", "Home")</p>

SuperSite/SuperSite/Views/Transaction/Edit.cshtml
@model SuperSite.Models.Transaction

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TransactionId)

        <div class="form-group">
            @Html.LabelFor(model => model.Reference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StockId, "Item", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StockId", new SelectList((System.Collections.IEnumerable)ViewData["Stocks"], "StockId", "Name"))
                @Html.ValidationMessageFor(model => model.StockId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SuperSite/SuperSite/Views/Transaction/Index.cshtml
@model IEnumerable<SuperSite.Models.Transaction>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PayPalCheckoutInfo.TransactionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PayPalCheckoutInfo.payer_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stock.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IPNDateRecieved) (Server local)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PayPalCheckoutInfo.TransactionId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PayPalCheckoutInfo.payer_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stock.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IPNDateRecieved) 
        </td>
        <td>           
            @Html.ActionLink("Details", "Details", new { id=item.TransactionId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TransactionId })
        </td>
    </tr>
}

</table>