SuperSite/SuperSite/Controllers/SiteController.cs
using SuperSite.Context;
using SuperSite.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SuperSite.Controllers
{
    [Authorize]
    public class SiteController : Controller
    {
        public Site siteConfig { get; set; }

        SiteContext db = new SiteContext();

        public void GetThemeAndSet()
        {
            SiteContext Sitedb = new SiteContext();
            siteConfig = Sitedb.Sites
                   .Where(b => b.isActive == 1)
                   .FirstOrDefault();
            if (siteConfig == null)
            {
                siteConfig = new Site();
                siteConfig.Theme = new Theme();
                siteConfig.Theme.CSSFileName = "css/style-blue.css";
            }
        }

        public ActionResult MakeActive(int id)
        {        
                siteConfig = db.Sites
           .Where(b => b.isActive == 1)
           .FirstOrDefault();
                if (siteConfig ==  null)
                {
                siteConfig = db.Sites.Find(id);
                siteConfig.isActive = 1;
                db.Entry(siteConfig).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }else
            {
                siteConfig.isActive = 0;
                db.Entry(siteConfig).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                Site siteTheme = db.Sites.Find(id);
                siteTheme.isActive = 1;
                db.Entry(siteTheme).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
               
        }
        public ActionResult CustomerIndex()
        {
            return View("ShopFront", db.Sites.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult Index()
        {   
            return View(db.Sites.ToList());
        }


        // GET: Site/Details/5
        public ActionResult Details(int? id)
        {
            if (id==null)
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Site site = db.Sites.Find(id);
            if (site == null)
            {
                return HttpNotFound();
            }return View(site);
               
        }

        // GET: Site/Create
        public ActionResult Create()
        {
            ViewData["Themes"] = db.Themes.ToList();
            ViewData["Stocks"] = db.Stocks.ToList();
            return View();
        }

        // POST: Site/Create
        [HttpPost]
        public ActionResult Create(Site siteTheme)
        {
            ViewData["Themes"] = db.Themes.ToList();
            ViewData["Stocks"] = db.Stocks.ToList();
            try
            {
                if (ModelState.IsValid)
                {
                    var fileName = "";
                    var path = "";

                    var file1 = Request.Files[0];
                    if (file1 != null && file1.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file1.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file1.SaveAs(path);
                        siteTheme.Filename1 = fileName;
                    }

                    var file2 = Request.Files[1];
                    if (file2 != null && file2.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file2.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file2.SaveAs(path);
                        siteTheme.Filename2 = fileName;
                    }
                    var file3 = Request.Files[2];
                    if (file3 != null && file3.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file3.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file3.SaveAs(path);
                        siteTheme.Filename3 = fileName;
                    }
                    var file4 = Request.Files[3];
                    if (file4 != null && file4.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file4.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file4.SaveAs(path);
                        siteTheme.Filename4 = fileName;
                    }
                    var file5 = Request.Files[4];
                    if (file5 != null && file5.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file5.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file5.SaveAs(path);
                        siteTheme.Filename5 = fileName;
                    }
                    var file6 = Request.Files[5];
                    if (file6 != null && file6.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file6.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file6.SaveAs(path);
                        siteTheme.Filename6 = fileName;
                    }
                    var file7 = Request.Files[6];
                    if (file7 != null && file7.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file7.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file7.SaveAs(path);
                        siteTheme.Filename7 = fileName;
                    }
                    var file8 = Request.Files[7];
                    if (file8 != null && file8.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file8.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file8.SaveAs(path);
                        siteTheme.Filename8 = fileName;
                    }
                    var file9 = Request.Files[8];
                    if (file9 != null && file9.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file9.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file9.SaveAs(path);
                        siteTheme.Filename9 = fileName;
                    }
                    var file10 = Request.Files[9];
                    if (file10 != null && file10.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file10.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file10.SaveAs(path);
                        siteTheme.Filename10 = fileName;
                    }
                    var file11 = Request.Files[10];
                    if (file11 != null && file11.ContentLength > 0)
                    {
                        fileName = Path.GetFileName(file11.FileName);
                        path = Path.Combine(Server.MapPath("~/img/"), fileName);
                        file11.SaveAs(path);
                        siteTheme.Filename11 = fileName;                    
                    }             
                    db.Sites.Add(siteTheme);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
    
                return View(siteTheme);
            }
            catch
            {
                
                return View();
            }
        }

        // GET: Site/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Site siteTheme = db.Sites.Find(id);
            if (siteTheme == null)
            {
                return HttpNotFound();
            }
            ViewData["Themes"] = db.Themes.ToList();
            ViewData["Stocks"] = db.Stocks.ToList();
            return View(siteTheme);
        }

        // POST: Site/Edit/5
        [HttpPost]
        public ActionResult Edit(Site siteTheme)
        {
            try
            {
                if (ModelState.IsValid)
                {                
                    db.Entry(siteTheme).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(siteTheme);
            }
            catch
            {
                return View();
            }
        }

        // GET: Site/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Site siteTheme = db.Sites.Find(id);
            if (siteTheme == null)
            {
                return HttpNotFound();
            }
            return View(siteTheme);
        }

        // POST: Site/Delete/5
        [HttpPost] //*Ignore siteThemee is only required to change the method signature, work with id instead*
        public ActionResult Delete(int? id, Site siteThemee)
        {
            try
            {
                Site siteTheme = new Site();
                if (ModelState.IsValid)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    siteTheme = db.Sites.Find(id);

SuperSite/SuperSite/Controllers/SupplierController.cs
using SuperSite.Context;
using SuperSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SuperSite.Controllers
{
    [Authorize]
    public class SupplierController : Controller
    {
        public Site activeTheme { get; set; }

        StockContext db = new StockContext();

        // GET: Supplier
        public ActionResult Index()
        {
      
            return View(db.Suppliers.ToList());
        }

        // GET: Supplier/Details/5
        public ActionResult Details(int? id)
        {
            if (id==null)
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Supplier Supplier = db.Suppliers.Find(id);
            if (Supplier == null)
            {
                return HttpNotFound();
            }return View(Supplier);
               
        }

        // GET: Supplier/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: Supplier/Create
        [HttpPost]
        public ActionResult Create(Supplier Supplier)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Suppliers.Add(Supplier);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(Supplier);
            }
            catch
            {
                return View();
            }
        }

        // GET: Supplier/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Supplier Supplier = db.Suppliers.Find(id);
            if (Supplier == null)
            {
                return HttpNotFound();
            }
            return View(Supplier);
        }

        // POST: Supplier/Edit/5
        [HttpPost]
        public ActionResult Edit(Supplier Supplier)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(Supplier).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(Supplier);
            }
            catch
            {
                return View();
            }
        }

        // GET: Supplier/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Supplier Supplier = db.Suppliers.Find(id);
            if (Supplier == null)
            {
                return HttpNotFound();
            }
            return View(Supplier);
        }

        // POST: Supplier/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id, Supplier Suppliere)
        {
            try
            {
                Supplier Supplier = new Supplier();
                if (ModelState.IsValid)
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Supplier = db.Suppliers.Find(id);
                    if (Supplier == null)
                    {
                        return HttpNotFound();
                    }
                    db.Suppliers.Remove(Supplier);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(Supplier);
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperSite/SuperSite/Views/Shared/AdminLayout.cshtml
@{
    ViewBag.Title = "Public Layout";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SuperSite</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SuperSite", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Stock", "Index", "Stock")</li>
                    <li>@Html.ActionLink("Transactions", "Index", "Transaction")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - www.simplygetsoftware.com</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

SuperSite/SuperSite/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="~/Content/NavbarLayout.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/Scripts/js/bootstrap.min.js"></script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    <style type="text/css">
                .ButtonLink
{
    background: url(https://www.paypalobjects.com/webstatic/en_US/i/btn/png/silver-pill-paypal-26px.png) no-repeat top left;
     display: block;
     width: 90px;
     height: 25px;
     text-indent: -9999px; /* hides the link text */
}
    </style>
    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Super Site", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Stock", "Index", "Stock")</li>
                    <li>@Html.ActionLink("Suppliers", "Index", "Supplier")</li>
                    <li>@Html.ActionLink("Transactions", "Index", "Transaction")</li>
                    @*<li>@Html.ActionLink("Users", "Index", "User")</li>*@
                    <li>@Html.ActionLink("Configuration", "Index", "Site")</li>
                </ul>
            </div>
        </div>
    </div>
    @*<div class="sidebar-nav">
        <div class="well" style="width:300px; padding: 8px 0;">
            <ul class="nav nav-list">
                <li class="nav-header">Admin Menu</li>
                <li><a href="index"><i class="icon-home"></i> Dashboard</a></li>
                <li><a href="#"><i class="icon-envelope"></i> Messages <span class="badge badge-info">4</span></a></li>
                <li><a href="#"><i class="icon-comment"></i> Comments <span class="badge badge-info">10</span></a></li>
                <li class="active"><a href="#"><i class="icon-user"></i> Members</a></li>
                <li class="divider"></li>
                <li><a href="#"><i class="icon-comment"></i> Settings</a></li>
                <li><a href="#"><i class="icon-share"></i> Logout</a></li>
            </ul>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
       
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SuperSite/SuperSite/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="~/Content/NavbarLayout.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/responsiveslides.min.js"></script>
    <script type="text/javascript">	    
			    $(function () {	
			      $("#slider1").responsiveSlides({
			        auto: true,
			        pager: true,
			        nav: true,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after</li>");
			        }
			      });

			    });
    </script>
</head>
<body>
    <header>
        <div class="container ">
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse" id="navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li><a class="" href="" title="about us">About Us</a> </li>
                            <li><a class="" href="" title="FAQ">FAQ</a> </li>
                            <li><a class="" href="">Contact Us</a> </li>
                            <li><a class="" href="">Blog</a> </li>
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>

            <div class="headerdetails">
                <a href="" class="logo pull-left"><img src="http://placehold.it/350x150?text=Company+logo" alt="" title=""></a>
                <div class="pull-right help">
                    <h3>Need Help? - Telephone# 1234556 </h3>
                   
                </div>
            </div>
            <!--navbar -->
            
                <div class="navbar navbar-default subnav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>               
                    </div>
                    <div class="navbar-collapse collapse" id="navbar-collapse-2">
                        <ul class="nav navbar-nav categorymenu">
                            <li><a href="#">Category A</a></li>
                            <li><a href="#">Category B</a></li>
                            <li><a href="#">Category C</a></li>                           
                            <li><a href="#">Category D</a></li>
                        </ul>
                    </div>
                </div>
              
            </div>

</header>
    <div class="container">
        @RenderBody()
        </div>
    <footer>      
        <div class="footer">
            <div class="container">
                <div class="footer-top">
                    <div class="col-md-6 footer-left">
                        <form>
                            <label>Subscribe to our blog</label>
                            <input type="text" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Email';}">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                    <div class="col-md-6 footer-right">
                        <p>@DateTime.Now.Year - www.simplygetsoftware.com</p>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </footer>       
        <hr />        
        @RenderSection("Scripts", required: false)
</body>
</html>

SuperSite/SuperSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>SuperSite - Development Project</title>
    <meta charset="utf-8">
    <meta name="author" content="SimplyGetSoftware.com">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"> 
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href=@ViewBag.CSSFileName>
    <link rel="shortcut icon" href="~/img/ico/32.png" sizes="32x32" type="image/png" />
    <link rel="apple-touch-icon-precomposed" href="~/img/ico/60.png" type="image/png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/img/ico/72.png" type="image/png" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="~/img/ico/120.png" type="image/png" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="~/img/ico/152.png" type="image/png" />
    <script type="text/javascript" src="~/js/modernizr.min.js"></script>

    
    @*@Scripts.Render("~/bundles/modernizr")*@
    <style type="text/css" >
        .navbar {z-index:1;
        }
        #menu-link {z-index:2;top:80px;
        }  

    </style>
   
    @*@Styles.Render("~/Content/css")*@
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <div class="container">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a style="color:white;background-color:black;">*Feature Developments*</a>                     
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })  
                @Html.ActionLink("About this site", "About", "Site", new { area = "" }, new { @class = "navbar-brand" })                         
            </div>
            <div class="navbar-collapse collapse">            
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
   
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - www.simplygetsoftware.com</p>
        </footer>
    </div>
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>